# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for CC
  pod 'RAMAnimatedTabBarController'

  pod 'lottie-ios'
  
  # Pods for network
  pod 'KeychainAccess'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  
  pod 'Socket.IO-Client-Swift', '~> 13.3.0'
  
end
